#!/bin/bash

if uname -m | grep -q 'aarch64' ;then
version=1.2.1
sudo apt install python3-pip
wget https://github.com/alienzhangyw/BlockPi/releases/download/v${version}/blockpi_${version}_arm64.deb
sudo dpkg -i blockpi_${version}_arm64.deb
else
version=1.2.1
sudo apt install python3-pip
wget https://github.com/alienzhangyw/BlockPi/releases/download/v${version}/blockpi_${version}_armv7l.deb
sudo dpkg -i blockpi_${version}_armv7l.deb
fi
