#!/bin/bash

if uname -m | grep -q 'aarch64' ;then
version=1.2.1
install_packages python3-pip https://github.com/alienzhangyw/BlockPi/releases/download/v${version}/blockpi_${version}_arm64.deb || exit 1
else
version=1.2.1
install_packages python3-pip https://github.com/alienzhangyw/BlockPi/releases/download/v${version}/blockpi_${version}_armv7l.deb || exit 1
fi
