#!/usr/bin/python3
import os
import sys
try:
  if sys.argv[1] == "--help":
    print("""Help:
pimarket --install <app name> - Install An App.
pimarket --help - Open this menu.
""")
except:
  print("""Help:
pimarket --install <app name> - Install An App.
pimarket --help - Open this menu.
""")
  exit()
if sys.argv[1] == "--install":
  try:
    os.system("bash ~/pimarket/apps/{0}/install".format(sys.argv[2]))
  except:
    print("ERROR: package not found")
if sys.argv[1] == "--list":
  try:
    print("Grabbing latest list from github...")
    os.system("wget https://raw.githubusercontent.com/MakePie/pimarket/main/apps.txt")
    print(open("./apps.txt").read())
    print("Clearing cache...")
    os.system("rm -rf ./apps.txt")
