#!/usr/bin/python3
import os
import sys
try:
  if sys.argv[1] == "--help":
    print("""Help:
pimarket --install <app name> - Install An App.
pimarket --help - Open this menu.
pimarket --ls - List all apps.
""")
except:
  print("""Help:
pimarket --install <app name> - Install An App.
pimarket --help - Open this menu.
pimarket --ls - List all apps.
""")
  exit()
if sys.argv[1] == "--install":
  try:
    os.system("cd ~ && bash /pimarket/apps/{0}/install".format(sys.argv[2]))
  except:
    print("ERROR: package not found")
if sys.argv[1] == "--ls":
  os.system("cd ~")
  print(open("/pimarket/apps.txt").read())
