#!/bin/bash

if uname -m | grep -q 'aarch64' ;then
echo "ERROR: Cannot install because architechure is aarch64. Install box64 instead."
else
echo installing box86...
wget https://github.com/ryanfortner/box86-debs-action/raw/master/2022-02-10/rpi4/box86-0.2.5_Linux-.deb
sudo dpkg -i box86-0.2.5_Linux-.deb
rm box86-0.2.5_Linux-.deb
echo box86 installed.
fi
